/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        'inter': ['Inter', 'sans-serif'],
        'instrument-serif': ['"Instrument Serif"', 'serif'],
      },
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        'custom-gold': '#fcc010',
        'custom-lime': '#33ff00',
        'custom-darkgray': '#a9a9a9',
        'custom-gainsboro': '#e6e6e6',
        "secondary-fixed-dim": "#c5c4de",
        "on-secondary": "#2e2f43",
        "on-tertiary": "#003640",
        "on-tertiary-container": "#005d6d",
        "surface": "#07151d",
        "on-secondary-fixed": "#191a2d",
        "tertiary-fixed-dim": "#0fd9fc",
        "surface-tint": "#f9bd09",
        "on-error-container": "#ffdad6",
        "on-background": "#d6e4f0",
        "secondary-fixed": "#e1e0fb",
        "on-surface": "#d6e4f0",
        "inverse-primary": "#785a00",
        "surface-container-low": "#101d26",
        "surface-variant": "#293640",
        "surface-dim": "#07151d",
        "outline": "#9c8f78",
        "on-primary-container": "#6c5000",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-secondary-fixed-variant": "#44455a",
        "inverse-on-surface": "#25323b",
        "surface-bright": "#2e3b44",
        "on-primary": "#3f2e00",
        "surface-container": "#14212a",
        "on-secondary-container": "#b7b6d0",
        "surface-container-highest": "#293640",
        "surface-container-lowest": "#031018",
        "on-primary-fixed": "#251a00",
        "on-primary-fixed-variant": "#5b4300",
        "error-container": "#93000a",
        "primary-fixed": "#ffdf9c",
        "tertiary": "#b6efff",
        "primary-container": "#fcc010",
        "primary-fixed-dim": "#f9bd09",
        "outline-variant": "#4f4632",
        "surface-container-high": "#1f2c34",
        "inverse-surface": "#d6e4f0",
        "secondary-container": "#47475d",
        "tertiary-fixed": "#abedff",
        "on-surface-variant": "#d3c5ac",
        "tertiary-container": "#1cdcff",
        "on-tertiary-fixed": "#001f26",
        "on-error": "#690005"
      },
      animation: {
        marquee: 'marquee 25s linear infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
    },
  },
  plugins: [],
}
